### ISSUE TITLE
Autoupdate Dependencies

### ISSUE THREAD

**Issue by hbetts** [conventional-changelog/get-pkg-repo#17]
@stevemao could we setup this repository with the [Renovate](https://github.com/apps/renovate) app to keep the project's dependencies up-to-date?

**Comment by stevemao** [comment]
Yes. Sorry for the late response :p

**Comment by hbetts** [comment]
Renovate has been added to this repository. That GitHub App will begin submitting dependency upgrades via pull requests as our dependencies release new major versions.
