### ISSUE TITLE
Need to bump @meow to version 10 to fix potential denial of service attack.

### ISSUE THREAD

**Issue by Flavyoo** [conventional-changelog/get-pkg-repo#60]
The trim-newlines package before 3.0.1 and 4.x before 4.0.1 for Node.js has an issue related to regular expression denial-of-service (ReDoS) for the .end() method. As a result the meow package should be updated to the version that uses 4.0.1 of trim-newLines which is version 10.0.0

**Comment by BitForger** [comment]
PR is automatically generated as #55. Can someone get this merged in? It's blocking deployments for anyone that has a policy of passing `npm audit` as a gate.

**Comment by snitin315** [comment]
Bump. Please update meow.

**Comment by snitin315** [comment]
You can also invite me to the repo if you need any help in maintenance.

**Comment by BitForger** [comment]
bump: cc @stevemao

**Comment by hutson** [comment]
cc @conventional-changelog/conventional-changelog for assistance

As a note, `trim-newlines` released their fix in version 4.0.1. Version 4.0.0 was added in `meow` version 10.0.0. 

Therefore, upgrading all the way to `meow` 10.0.0 is a hard requirement. `meow` 10 switched to ESM, so the upgrade is not trivial.

**Comment by alanjcharles** [comment]
any timeline on this? Can't resolve this security vulnerability which is blocking other progress this sprint. Thanks so much :)

**Comment by HenriqueSilverio** [comment]
Currently, to don't get stuck with it, I using this workaround:

```json
{
  "name": "your-package-name",
  "scripts": {
    "preinstall": "npx npm-force-resolutions"
  },
  "devDependencies": {},
  "resolutions": {
    "trim-newlines": "^3.0.1"
  }
}
```

**Comment by HenriqueSilverio** [comment]
@hutson I'm taking a quick look into possible ways to solve this issue.

`meow` introduced breaking changes in [v8](https://github.com/sindresorhus/meow/releases/tag/v8.0.0) and [v9](https://github.com/sindresorhus/meow/releases/tag/v9.0.0) as well.

Currently, [`conventional-changelog/get-pkg-repo` is using `meow` v7](https://github.com/conventional-changelog/get-pkg-repo/blob/master/package.json#L45).

Do you think we could easily upgrade to v9? I think so, but may be I missing some point, so asking you...

If we upgrade `meow` to v9, I could send them a propose to do a [maintenance release](https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/maintenance-releases.md#publishing-maintenance-releases) of v9, with this `trim-newlines` fix...

**Comment by billchurch** [comment]
> Currently, to don't get stuck with it, I'm using this workaround:
> 
> ```json
> {
>   "name": "your-package-name",
>   "scripts": {
>     "preinstall": "npx npm-force-resolutions"
>   },
>   "devDependencies": {
>     "eslint": "^7.27.0",
>     "eslint-config-airbnb-base": "^14.2.1",
>     "eslint-plugin-import": "^2.23.3",
>     "lerna": "^4.0.0"
>   },
>   "resolutions": {
>     "trim-newlines": "^3.0.1"
>   }
> }
> ```
> 
> Just ignore my `devDependencies` property. The point here is the use of [`npm-force-resolutions`](https://www.npmjs.com/package/npm-force-resolutions).

If you have a package-lock.json that might interfere so you'll need to rebuild that as well. but good workaround until it's officially resolved.

**Comment by bramjoosten** [comment]
bump

**Comment by angelogiuseppe** [comment]
To anyone experiencing this issue, feel free to try: https://www.npmjs.com/package/force-resolutions

**Just change:**

```json
"preinstall": "npx npm-force-resolutions"
```
**To:**

```json
"preinstall": "npx force-resolutions"
```


npx force-resolutions does not run when no package-lock.json is detected, and allows the next command inline to be executed as normal. This is useful when installing dependencies for a package that has been already published where package-lock.json is not available.

Feedback and PR's are welcome

**Comment by githrdw** [comment]
Well, why waiting for `meow` if there are other perfect candidates that still support the 'old' CJS, packages like [yargs/yargs](https://github.com/yargs/yargs)?
I created a proposal the form of a PR where `meow` is replaced with `yargs` https://github.com/conventional-changelog/get-pkg-repo/pull/62

Why? I really don't like that Dependabot is unhappy because of [Lerna](https://github.com/lerna/lerna/issues/2925) and I think `yargs` will support CJS in the future where `meow` already dropped it.

(fun fact; @bcoe maintains `yargs` and he is also member of this organisation, I'm sure he will like it :D)

**Comment by jimmywarting** [comment]
I think we should update to ESM and drop support for node < 12.20 as well...

**Comment by neverendingqs** [comment]
> Well, why waiting for `meow` if there are other perfect candidates that still support the 'old' CJS, packages like [yargs/yargs](https://github.com/yargs/yargs)?
> I created a proposal the form of a PR where `meow` is replaced with `yargs` #62
> 
> Why? I really don't like that Dependabot is unhappy because of [Lerna](https://github.com/lerna/lerna/issues/2925) and I think `yargs` will support CJS in the future where `meow` already dropped it.
> 
> (fun fact; @bcoe maintains `yargs` and he is also member of this organisation, I'm sure he will like it :D)

It looks like this may have been resolved with https://github.com/conventional-changelog/get-pkg-repo/pull/62, and can be closed?

**Comment by neverendingqs** [comment]
Sorry looks like we still need to cut a release: https://github.com/conventional-changelog/get-pkg-repo/pull/62#issuecomment-911866965

**Comment by hutson** [comment]
Version 4.2.0 of `get-pkg-release` has been published - https://www.npmjs.com/package/get-pkg-repo/v/4.2.0

Please let us know if there are any issues with updating to that release.
